version: '3'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: timoheihe # same with RDS
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres # same with RDS
    networks:
      - default
    ports:
      - 6543:5432
    volumes:
      - ./local-data/db:/var/lib/postgresql/data
      - ./seeds/seed.sql:/seed.sql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db
    env_file:
      - ./server/.env.dev